In [5]:
import pandas as pd

df = pd.read_csv("online_shoppers_intention.csv")

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

Dataset loaded successfully!
Rows and columns: (12330, 18)

First 5 rows:

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [6]:
print("Missing values in each column:")
print(df.isnull().sum())

print("\nTotal missing values:", df.isnull().sum().sum())

Missing values in each column:
Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

Total missing values: 0

In [7]:
print("Total duplicate rows:", df.duplicated().sum())

Total duplicate rows: 125

In [8]:
df = df.drop_duplicates()

print("Rows after removing duplicates:", df.shape[0])
print("Remaining duplicate rows:", df.duplicated().sum())

Rows after removing duplicates: 12205
Remaining duplicate rows: 0

In [9]:
print(df.dtypes)

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                          str
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                    str
Weekend                       bool
Revenue                       bool
dtype: object

In [10]:
print("Minimum and maximum values:")
print(df.describe())

Minimum and maximum values:
       Administrative  Administrative_Duration  Informational  \
count    12205.000000             12205.000000   12205.000000
mean         2.338878                81.646331       0.508726
std          3.330436               177.491845       1.275617
min          0.000000                 0.000000       0.000000
25%          0.000000                 0.000000       0.000000
50%          1.000000                 9.000000       0.000000
75%          4.000000                94.700000       0.000000
max         27.000000              3398.750000      24.000000

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
count            12205.000000    12205.000000             12205.000000
mean                34.825454       32.045637              1206.982457
std                141.424807       44.593649              1919.601400
min                  0.000000        0.000000                 0.000000
25%                  0.000000        8.000000               193.000000
50%                  0.000000       18.000000               608.942857
75%                  0.000000       38.000000              1477.154762
max               2549.375000      705.000000             63973.522230

        BounceRates     ExitRates    PageValues    SpecialDay  \
count  12205.000000  12205.000000  12205.000000  12205.000000
mean       0.020370      0.041466      5.949574      0.061942
std        0.045255      0.046163     18.653671      0.199666
min        0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.014231      0.000000      0.000000
50%        0.002899      0.025000      0.000000      0.000000
75%        0.016667      0.048529      0.000000      0.000000
max        0.200000      0.200000    361.763742      1.000000

       OperatingSystems       Browser        Region   TrafficType
count      12205.000000  12205.000000  12205.000000  12205.000000
mean           2.124211      2.357804      3.153298      4.073904
std            0.906823      1.710114      2.402340      4.016654
min            1.000000      1.000000      1.000000      1.000000
25%            2.000000      2.000000      1.000000      2.000000
50%            2.000000      2.000000      3.000000      2.000000
75%            3.000000      2.000000      4.000000      4.000000
max            8.000000     13.000000      9.000000     20.000000

In [11]:
print("Unique months:")
print(df["Month"].unique())

Unique months:
<StringArray>
['Feb', 'Mar', 'May', 'Oct', 'June', 'Jul', 'Aug', 'Nov', 'Sep', 'Dec']
Length: 10, dtype: str

In [12]:
df["Month"] = df["Month"].replace({
    "June": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
})

print("Unique months after cleaning:")
print(df["Month"].unique())

Unique months after cleaning:
<StringArray>
['Feb', 'Mar', 'May', 'Oct', 'Jun', 'Jul', 'Aug', 'Nov', 'Sep', 'Dec']
Length: 10, dtype: str

In [13]:
print("Visitor types:")
print(df["VisitorType"].value_counts())

Visitor types:
VisitorType
Returning_Visitor    10431
New_Visitor           1693
Other                   81
Name: count, dtype: int64

In [14]:
print("Revenue distribution:")
print(df["Revenue"].value_counts())

print("\nRevenue percentage:")
print(df["Revenue"].value_counts(normalize=True) * 100)

Revenue distribution:
Revenue
False    10297
True      1908
Name: count, dtype: int64

Revenue percentage:
Revenue
False    84.367063
True     15.632937
Name: proportion, dtype: float64

In [15]:
print("Unique values in Weekend:")
print(df["Weekend"].unique())

print("\nUnique values in Revenue:")
print(df["Revenue"].unique())

print("\nUnique values in VisitorType:")
print(df["VisitorType"].unique())

Unique values in Weekend:
[False  True]

Unique values in Revenue:
[False  True]

Unique values in VisitorType:
<StringArray>
['Returning_Visitor', 'New_Visitor', 'Other']
Length: 3, dtype: str

In [16]:
print("Month values and their counts:")
print(df["Month"].value_counts())

Month values and their counts:
Month
May    3329
Nov    2982
Mar    1860
Dec    1706
Oct     549
Sep     448
Aug     433
Jul     432
Jun     285
Feb     181
Name: count, dtype: int64

In [17]:
numeric_df = df.select_dtypes(include="number")

print("Negative values in each numerical column:")
print((numeric_df < 0).sum())

Negative values in each numerical column:
Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
dtype: int64

In [18]:
text_columns = df.select_dtypes(include="object")

print("Unnecessary spaces in each text column:")
print(text_columns.apply(lambda col: col.str.strip().ne(col).sum()))

Unnecessary spaces in each text column:
Month          0
VisitorType    0
dtype: int64

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11484\3155839905.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object")

In [19]:
df.to_csv("online_shoppers_intention_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")
print("Final dataset shape:", df.shape)

Cleaned dataset saved successfully!
Final dataset shape: (12205, 18)

In [20]:
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

Dataset shape: (12205, 18)

Column names:
['Administrative', 'Administrative_Duration', 'Informational', 'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration', 'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month', 'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType', 'Weekend', 'Revenue']

Data types:
Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                          str
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                    str
Weekend                       bool
Revenue                       bool
dtype: object

In [21]:
df.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12205.000000,12205.000000,12205.000000,12205.000000,12205.000000,12205.000000,12205.000000,12205.000000,12205.000000,12205.000000,12205.000000,12205.000000,12205.000000,12205.000000
mean,2.338878,81.646331,0.508726,34.825454,32.045637,1206.982457,0.020370,0.041466,5.949574,0.061942,2.124211,2.357804,3.153298,4.073904
std,3.330436,177.491845,1.275617,141.424807,44.593649,1919.601400,0.045255,0.046163,18.653671,0.199666,0.906823,1.710114,2.402340,4.016654
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,8.000000,193.000000,0.000000,0.014231,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,9.000000,0.000000,0.000000,18.000000,608.942857,0.002899,0.025000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,94.700000,0.000000,0.000000,38.000000,1477.154762,0.016667,0.048529,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

In [22]:
print("Purchase outcomes:")
print(df["Revenue"].value_counts())

print("\nPurchase outcome percentages:")
print((df["Revenue"].value_counts(normalize=True) * 100).round(2))

Purchase outcomes:
Revenue
False    10297
True      1908
Name: count, dtype: int64

Purchase outcome percentages:
Revenue
False    84.37
True     15.63
Name: proportion, dtype: float64

In [23]:
print("Visitor type counts:")
print(df["VisitorType"].value_counts())

print("\nVisitor type percentages:")
print(
    (df["VisitorType"].value_counts(normalize=True) * 100).round(2)
)

Visitor type counts:
VisitorType
Returning_Visitor    10431
New_Visitor           1693
Other                   81
Name: count, dtype: int64

Visitor type percentages:
VisitorType
Returning_Visitor    85.46
New_Visitor          13.87
Other                 0.66
Name: proportion, dtype: float64

In [24]:
print(df["VisitorType"].value_counts())
print((df["VisitorType"].value_counts(normalize=True) * 100).round(2))

VisitorType
Returning_Visitor    10431
New_Visitor           1693
Other                   81
Name: count, dtype: int64
VisitorType
Returning_Visitor    85.46
New_Visitor          13.87
Other                 0.66
Name: proportion, dtype: float64

In [25]:
print("Shopping sessions by month:")
print(df["Month"].value_counts())

Shopping sessions by month:
Month
May    3329
Nov    2982
Mar    1860
Dec    1706
Oct     549
Sep     448
Aug     433
Jul     432
Jun     285
Feb     181
Name: count, dtype: int64

In [26]:
print("Weekend vs weekday sessions:")
print(df["Weekend"].value_counts())

print("\nPercentages:")
print((df["Weekend"].value_counts(normalize=True) * 100).round(2))

Weekend vs weekday sessions:
Weekend
False    9346
True     2859
Name: count, dtype: int64

Percentages:
Weekend
False    76.58
True     23.42
Name: proportion, dtype: float64

In [27]:
print(pd.crosstab(df["VisitorType"], df["Revenue"]))

Revenue            False  True
VisitorType
New_Visitor         1271    422
Other                 65     16
Returning_Visitor   8961   1470

In [28]:
print(pd.crosstab(df["Month"], df["Revenue"]))

Revenue  False  True
Month
Aug        357     76
Dec       1490    216
Feb        178      3
Jul        366     66
Jun        256     29
Mar       1668    192
May       2964    365
Nov       2222    760
Oct        434    115
Sep        362     86